export const SELECTORS = {
  introSection: 'section#intro',
  introTitle: '.intro__title',
  introSubtitleAccent: '#intro .intro__subtitle-accent',
  viewWorkButton: 'button:has-text("View Work")',
  contactButton: 'button:has-text("Contact")',
  projectsSection: 'section#projects',
  blogSection: 'section#blog',
  contactSection: 'section#contact',
  sidebarBlogButton: '.sidebar__item:has-text("Blog")',
  sidebarContactButton: '.sidebar__item:has-text("Contact")',
  bottomBlogButton: '.bottom-nav__item:has-text("Blog")',
  blogItems: 'app-blog-item .blog-card',
  resumeLink: '.sidebar__resume',
  githubSocialLink: '.sidebar__social a[aria-label="GitHub"]',
  instagramSocialLink: '.sidebar__social a[aria-label="Instagram"]',
  facebookSocialLink: '.sidebar__social a[aria-label="Facebook"]',
  linkedinSocialLink: '.sidebar__social a[aria-label="LinkedIn"]',
  repoStatsDesktop: '.repo.repo--desktop',
  repoStatsDesktopExpand: '.repo--desktop .repo__expand',
  repoStatsStarValue: '.repo--desktop .repo__stat:first-child span',
  repoStatsForkValue: '.repo--desktop .repo__stat:nth-child(2) span',
};
